version: '3.8'
services:
  pptx-to-pdf-server:
    build: ./backend  
    ports:
      - "8000:8000"
      - "5678:5678" # Map debugpy port  
    volumes:
      - ./backend:/app  
    env_file:
      - .env  
  unoserver:
    image: libreofficedocker/libreoffice-unoserver:3.19-9c28c22 
    ports:
      - "2002:2002" 